######################################################################
##
## Filename: testUart.udo
## Created on: Fri Jan 18 0:35:06 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
