######################################################################
##
## Filename: TestBytesFifo.udo
## Created on: Fri Jan 18 13:02:40 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
